sudo: required

services:
  - docker

language: go

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

script: 
  - chmod +x script/build.sh
  - script/build.sh

deploy:
  provider: script
  script: 
    - chmod +x script/deploy.sh
    - script/deploy.sh
  on:
    branch: master