sudo: required

services:
  - docker

language: go

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

script: 
  - echo $HOME
  - chmod +x script/build.sh
  - script/build.sh

deploy:
  provider: script
  script: bash script/deploy.sh
  on:
    branch: master
  skip_cleanup: true
