// Package database deals with the initialization
// of our database connection.
package database

import (
	"database/sql"
	"errors"
	"strings"
	"time"
)

// Database Errors
//
// These are the errors that can be generated by our databases.
var (
	// ErrDuplicate refers to an error generated when
	// a unique constraint is violated.
	ErrDuplicate = errors.New("database: duplicate entry")
)

// DB wraps the underlying database connection, allowing
// for methods to be executed through it.
//
// The purpose of this abstraction is to allow for the use of different
// databases without forcing the user to undergo a major refactor.
//
// For the time being, planned support is for the following databases:
// * PostgreSQL (Currently Supported / Used by MangoHacks 2019)
// * MongoDB
type DB struct {
	postgres *sql.DB
}

// InsertPreregistration inserts a new preregistration into the appropriate
// database.
func (db *DB) InsertPreregistration(email string) error {
	if db.postgres != nil {
		return db.postgresInsertPreregistrations(email)
	}
	return nil
}

func (db *DB) SelectPreregistration() error {
	return nil
}

func (db *DB) postgresInsertPreregistrations(email string) error {
	q := `INSERT INTO preregistrations(email, timestamp) 
	VALUES($1, $2) 
	RETURNING email`
	if _, err := db.postgres.Exec(q, email, time.Now()); err != nil {
		if strings.Contains(err.Error(), "duplicate key value violates unique constraint") {
			return ErrDuplicate
		}
		return err
	}
	return nil
}

func (db *DB) postgresSelectPreregistrations() error {
	return nil
}
